export const actionTypes = {
  QUERY: "QUERY",
  QUERY_STARS: "QUERY_STARS",
  QUERY_FORKED: "QUERY_FORKED",
  QUERY_LICENSE: "QUERY_LICENSE",
  LOADER: "LOADER",
  GET_RESULTS: "GET_RESULTS",
  ERROR: "ERROR",
  NO_RESULTS: "NO_RESULTS"
};
