export const actionTypes = {
  URL: "URL",
  KEYWORDS: "KEYWORDS",
  STARS: "STARS",
  FORKED: "FORKED",
  LICENSE: "LICENSE",
  PAGE: "PAGE",
  LOADER: "LOADER",
  RESULTS: "RESULTS",
  ERROR: "ERROR",
  NO_RESULTS: "NO_RESULTS"
};
